import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

class EmailConfig:
    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587
    SMTP_USERNAME = os.getenv("GMAIL_USERNAME")
    SMTP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "xploiteye@gmail.com")

async def send_scan_report_email(to_email: str, scan_id: str, scan_result: dict, pdf_path: str):
    """
    Sends the professional PDF report and scan summary via email.
    """
    if not EmailConfig.SMTP_USERNAME or not EmailConfig.SMTP_PASSWORD:
        logger.error("Email credentials missing in .env")
        return False

    target_url = scan_result.get("target", "Unknown")
    severity_counts = {}
    for f in scan_result.get("findings", []):
        sev = f.get("severity", "Low").upper()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    subject = f"[XploitEye] Security Assessment Report - {target_url}"
    
    # Create HTML Email Body
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="background-color: #1A1A1A; color: #FFFFFF; padding: 20px; text-align: center;">
            <h1 style="margin: 0;">XploitEye Security</h1>
            <p style="margin: 0; color: #32CD32;">Automated Vulnerability Assessment</p>
        </div>
        
        <div style="padding: 20px;">
            <h2>Assessment Complete: {target_url}</h2>
            <p>The security scan for <b>{target_url}</b> has completed successfully.</p>
            
            <div style="background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0;">
                <h3 style="margin-top: 0;">Scan Summary</h3>
                <ul style="list-style: none; padding: 0;">
                    <li><b>Scan ID:</b> {scan_id}</li>
                    <li><b>Target Domain:</b> {target_url}</li>
                    <li><b>Duration:</b> {scan_result.get('scan_duration_sec', 0):.2f} seconds</li>
                </ul>
            </div>

            <div style="background-color: #fff; border: 1px solid #ddd; padding: 15px; border-radius: 5px;">
                <h3 style="margin-top: 0;">Finding Stats</h3>
                <ul style="list-style: none; padding: 0;">
                    <li style="color: #8B0000;"><b>Critical:</b> {severity_counts.get('CRITICAL', 0)}</li>
                    <li style="color: #FF0000;"><b>High:</b> {severity_counts.get('HIGH', 0)}</li>
                    <li style="color: #FFA500;"><b>Medium:</b> {severity_counts.get('MEDIUM', 0)}</li>
                    <li style="color: #008000;"><b>Low:</b> {severity_counts.get('LOW', 0)}</li>
                </ul>
            </div>

            <p style="margin-top: 20px;">Please find the detailed ISO-standard PDF report attached to this email.</p>
            
            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 12px; color: #777; text-align: center;">
                Generated by XploitEye Security System | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </p>
        </div>
    </body>
    </html>
    """

    # Setup Message
    msg = MIMEMultipart()
    msg['From'] = EmailConfig.DEFAULT_FROM_EMAIL
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(html_body, 'html'))

    # Attach PDF
    if os.path.exists(pdf_path):
        try:
            with open(pdf_path, "rb") as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', f"attachment; filename= XploitEye_Report_{target_url.replace('https://', '').replace('/', '_')}.pdf")
                msg.attach(part)
        except Exception as e:
            logger.error(f"Failed to attach PDF: {e}")

    # Send Email
    try:
        server = smtplib.SMTP(EmailConfig.SMTP_SERVER, EmailConfig.SMTP_PORT)
        server.starttls()
        server.login(EmailConfig.SMTP_USERNAME, EmailConfig.SMTP_PASSWORD)
        server.send_message(msg)
        server.quit()
        logger.info(f"Email sent successfully to {to_email}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False
